# Generated by Django 4.2.4 on 2023-08-11 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreActividad', models.CharField(max_length=25)),
                ('fechaActividad', models.DateTimeField()),
                ('ubicacionActividad', models.CharField(max_length=10)),
                ('responsableActividad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreHotel', models.CharField(max_length=25)),
                ('ubicacionHotel', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Precios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoHabitacion', models.CharField(choices=[('Individual', 'Individual'), ('Doble', 'Doble'), ('Triple', 'Triple')], max_length=15)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='ComplementoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotoPerfil', models.CharField(max_length=100)),
                ('tecOrigen', models.CharField(max_length=50)),
                ('hospedaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
