# Generated by Django 4.2.4 on 2023-11-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnologico',
            name='logo',
            field=models.ImageField(blank=True, default='user.jpg', upload_to='logos/'),
        ),
    ]
