# Generated by Django 4.2.4 on 2023-10-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_tecnologico_registroasistencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complementouser',
            name='tipoUsuario',
            field=models.CharField(default='Visitante', max_length=20),
        ),
    ]
