# Generated by Django 4.2.4 on 2023-11-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_tecnologico_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnologico',
            name='nombreTec',
            field=models.CharField(max_length=100),
        ),
    ]
