# Generated by Django 4.2.4 on 2023-11-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_tecnologico_nombretec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnologico',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
