# Generated by Django 4.2.4 on 2023-10-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_complementouser_tipousuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complementouser',
            name='tipoUsuario',
        ),
        migrations.AddField(
            model_name='informacionextrausuario',
            name='tipoUsuario',
            field=models.CharField(default='Visitante', max_length=20),
        ),
    ]
