# Generated by Django 4.2.4 on 2023-11-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_tecnologico_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionextrausuario',
            name='evento',
            field=models.CharField(choices=[('Ciencias básica', 'Ciencias básica'), ('Economico Administrativas', 'Economico Administrativas')], max_length=100, null=True),
        ),
    ]
