# Generated by Django 4.2.4 on 2023-11-07 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_complementouser_tipousuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionextrausuario',
            name='habitacion',
            field=models.CharField(default='h1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informacionextrausuario',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.hotel'),
            preserve_default=False,
        ),
    ]
