# Generated by Django 4.2.4 on 2023-11-07 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_informacionextrausuario_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComplementoUser',
        ),
    ]
