# Generated by Django 4.2.4 on 2023-11-10 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_informacionextrausuario_habitacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('curp', models.CharField(max_length=20)),
                ('telefonoEmergencia', models.CharField(blank=True, max_length=15, null=True)),
                ('condicion', models.CharField(blank=True, max_length=200, null=True)),
                ('tipoUsuario', models.CharField(choices=[('Visitante', 'Visitante'), ('Organizador', 'Organizador'), ('Autoridad', 'Autoridad'), ('Asesor', 'Asesor'), ('Participante Ciencias Básicas', 'Participante Ciencias Básicass'), ('Participante Económico Administrativo', 'Participante Económico Administrativo')], default='Visitante', max_length=100)),
                ('habitacion', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen', models.ImageField(blank=True, default='user.jpg', null=True, upload_to='fotos/')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.hotel')),
            ],
        ),
        migrations.RemoveField(
            model_name='informacionextrausuario',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='informacionextrausuario',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='informacionextrausuario',
            name='habitacion',
        ),
        migrations.RemoveField(
            model_name='informacionextrausuario',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='informacionextrausuario',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='informacionextrausuario',
            name='modalidad',
        ),
        migrations.RemoveField(
            model_name='informacionextrausuario',
            name='tecOrigen',
        ),
        migrations.RemoveField(
            model_name='informacionextrausuario',
            name='tipoUsuario',
        ),
        migrations.AddField(
            model_name='informacionextrausuario',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.DeleteModel(
            name='Tecnologico',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='informacionTec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.informacionextrausuario'),
        ),
    ]
