# Generated by Django 4.2.4 on 2023-11-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_usuarios_remove_informacionextrausuario_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionextrausuario',
            name='logo',
            field=models.ImageField(blank=True, default='defaultLogo.png', null=True, upload_to='logos/'),
        ),
    ]
