# Generated by Django 4.2.4 on 2023-11-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_informacionextrausuario_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='condicion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
