# Generated by Django 4.2.4 on 2023-11-14 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_usuarios_condicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroasistencia',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usuarios'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='curp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='tipoUsuario',
            field=models.CharField(choices=[('Visitante', 'Visitante'), ('Organizador', 'Organizador'), ('Autoridad', 'Autoridad'), ('Asesor', 'Asesor'), ('Participante Ciencias Básicas', 'Participante Ciencias Básicas'), ('Participante Económico Administrativo', 'Participante Económico Administrativo')], default='Visitante', max_length=100),
        ),
    ]
